### ISSUE TITLE
Provide position through PSDK

### ISSUE THREAD

**Issue by JulienSOCQUET** [dji-sdk/Payload-SDK-Doc#5]
Hi,

I have a M200 V2 that I want to fly in GPS-denied environments with the support of a payload running a SLAM algorithm. Is there a way to provide the position estimate from the SLAM to the FCU through the PSDK?

Regards,

Julien

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/47059'>Zendesk ticket #47059</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The aircraft can not be controlled from Payload via PSDK.

If you want to contorl the aircraft moving from the device that is mounted on aircraft, please refer to OSDK.

https://developer.dji.com/document/1be2b992-5862-4eb5-819b-dd6036f76133

Best Regards,
Cheney zeng<br><p><em><small>°°°</small></em></p>
